import {useCallback,useEffect,useRef,useState} from 'react'
import {ArrowLeft,Plus,Search,X,ImagePlus,LoaderCircle,Pencil,Trash2,Link,Copy} from 'lucide-react'
import {memeRequest,memeImage} from '../services/memes'
import './MemePocket.css'
function Picture({meme}){
 const [src,setSrc]=useState(''),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0),[visible,setVisible]=useState(false)
 const box=useRef(null)
 useEffect(()=>{if(!globalThis.IntersectionObserver){setVisible(true);return}const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect()}},{rootMargin:'150px'});if(box.current)observer.observe(box.current);return()=>observer.disconnect()},[])
 useEffect(()=>{if(!visible)return;const controller=new AbortController();let url,alive=true;setFailed(false);memeImage(meme.id,controller.signal).then(value=>{url=value;if(alive)setSrc(value);else URL.revokeObjectURL(value)}).catch(e=>{if(e.name!=='AbortError'&&alive)setFailed(true)});return()=>{alive=false;controller.abort();if(url)URL.revokeObjectURL(url)}},[meme.id,retry,visible])
 return <div ref={box} className="mp-loaded-picture">{src?<img src={src} alt={meme.name} loading="lazy"/>:failed?<button onClick={()=>setRetry(v=>v+1)}>图片加载失败，点此重试</button>:<LoaderCircle className="mp-spin" size={22}/>}</div>
}
export default function MemePocket({onBack}){
 const [items,setItems]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[name,setName]=useState(''),[tags,setTags]=useState(''),[busy,setBusy]=useState(false),[deleteId,setDeleteId]=useState(null),[pair,setPair]=useState(null),[copied,setCopied]=useState(false)
 const input=useRef(null),dialog=useRef(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems((await memeRequest('api')).memes)}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open])
 function start(m){setEditing(m||null);setName(m?.name||'');setTags(m?.tags||'');setFile(null);setError('');setOpen(true)}
 async function save(e){e.preventDefault();if(!editing&&!file){setError('先选一张图片吧。');return}setBusy(true);setError('');try{let data;if(editing){data=await memeRequest('api/'+editing.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,tags})});setItems(v=>v.map(m=>m.id===data.meme.id?data.meme:m))}else{const form=new FormData();form.set('file',file);form.set('name',name);form.set('tags',tags);data=await memeRequest('api',{method:'POST',body:form});setItems(v=>[data.meme,...v])}setOpen(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(id){setBusy(true);setError('');try{await memeRequest('api/'+id,{method:'DELETE'});setItems(v=>v.filter(m=>m.id!==id));setDeleteId(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function connect(){setBusy(true);setError('');try{setPair(await memeRequest('pair',{method:'POST'}));setCopied(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(pair.code);setCopied(true)}catch{setError('没能自动复制，请长按连接码复制。')}}
 const terms=query.trim().toLowerCase().split(/[,，、\s]+/).filter(Boolean),visible=items.filter(m=>!terms.length||terms.some(t=>(m.name+' '+m.tags).toLowerCase().includes(t)))
 return <section className="meme-pocket"><header><button aria-label="返回" onClick={onBack}><ArrowLeft size={21}/></button><h1>表情包口袋</h1><button className="mp-primary" onClick={()=>start()}><Plus size={17}/>收一张</button></header>
 <div className="mp-scroll"><p className="mp-intro">给喜欢的表情包起个名字、贴几个标签。</p><label className="mp-search"><Search size={18}/><input aria-label="搜索表情包" placeholder="搜名字或标签，比如「贴贴」" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空" onClick={()=>setQuery('')}><X size={16}/></button>}</label>
 <div className="mp-summary"><span>{visible.length} 张表情包</span><button disabled={busy} onClick={connect}><Link size={15}/>连接 ChatGPT</button></div>
 {error&&!open&&<div role="alert" className="mp-error">{error}<button onClick={load}>重试</button></div>}
 {pair&&<div className="mp-pair"><div><strong>把连接码发给哥哥</strong><button aria-label="关闭连接码" onClick={()=>setPair(null)}><X size={16}/></button></div><p>只授权读取这份表情包库，10 分钟内有效。生成新码会替换之前的连接。</p><code>{pair.code}</code><button disabled={busy} onClick={copy}><Copy size={15}/>{copied?'已复制':'复制连接码'}</button><button className="mp-revoke" disabled={busy} onClick={async()=>{setBusy(true);try{await memeRequest('pair',{method:'DELETE'});setPair(null)}catch(e){setError(e.message)}finally{setBusy(false)}}}>断开读取授权</button></div>}
 {loading?<div className="mp-empty"><LoaderCircle className="mp-spin"/>正在打开口袋…</div>:<div className="mp-grid">{visible.map(m=><article key={m.id}><div className="mp-picture"><Picture meme={m}/>{m.mime==='image/gif'&&<span>GIF</span>}</div><h2>{m.name}</h2><div className="mp-tags">{m.tags.split(' ').filter(Boolean).map(t=><button key={t} onClick={()=>setQuery(t)}>#{t}</button>)}</div><div className="mp-actions"><button onClick={()=>start(m)}><Pencil size={14}/>改标签</button><button aria-label={'删除'+m.name} onClick={()=>setDeleteId(m.id)}><Trash2 size={15}/></button></div>{deleteId===m.id&&<div className="mp-delete"><span>删除这张？</span><button disabled={busy} onClick={()=>setDeleteId(null)}>留下</button><button disabled={busy} onClick={()=>remove(m.id)}>删除</button></div>}</article>)}{!query&&<button className="mp-add" onClick={()=>start()}><ImagePlus size={28}/><strong>收一张喜欢的</strong><small>图片或 GIF · 最多 5 MB</small></button>}</div>}
 {!loading&&query&&!visible.length&&<div className="mp-empty">这个标签还没有表情包，换个词试试。</div>}<p className="mp-tip">标签可以写情绪、场景和角色，比如「贴贴 抱抱 撒娇 猪猪 小狗」。</p></div>
 <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setOpen(false)}} onClose={()=>setOpen(false)}><form onSubmit={save}><div className="mp-dialog-head"><h2>{editing?'改名字和标签':'收一张表情包'}</h2><button type="button" aria-label="关闭" disabled={busy} onClick={()=>setOpen(false)}><X size={20}/></button></div>{!editing&&<><input hidden ref={input} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setError('单张图片最多 5 MB。');return}setFile(f);setName(v=>v||f.name.replace(/\.[^.]+$/,''));setError('')}}/><button type="button" className="mp-picker" disabled={busy} onClick={()=>input.current?.click()}>{preview?<img src={preview} alt="待上传的表情包"/>:<><ImagePlus size={30}/><span>从相册选一张</span></>}</button></>}
 <label>名字<input required maxLength={80} placeholder="猪猪贴狗狗" value={name} onChange={e=>setName(e.target.value)}/></label><label>标签<input maxLength={400} placeholder="贴贴 抱抱 撒娇 猪猪 小狗" value={tags} onChange={e=>setTags(e.target.value)}/><small>用空格或逗号隔开。</small></label><div className="mp-suggest">{['贴贴','开心','委屈','晚安','撒娇','猪猪'].map(t=><button type="button" key={t} onClick={()=>setTags(v=>[...new Set([...v.split(/[,，、\s]+/).filter(Boolean),t])].join(' '))}>+{t}</button>)}</div>{error&&<p role="alert" className="mp-error">{error}</p>}<button className="mp-primary mp-save" disabled={busy}>{busy?'正在保存…':'收好'}</button></form></dialog></section>
}
