import {describe,it,expect} from 'vitest'
import {handleMemeRequest} from './memes.js'
function kv(){const values=new Map();return {async get(k,type){const v=values.get(k);if(v===undefined)return null;if(type==='json')return JSON.parse(v);if(type==='arrayBuffer')return v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength);return v},async put(k,v){values.set(k,v)},async delete(k){values.delete(k)},async list({prefix,limit=1000,cursor='0'}){const all=[...values.keys()].filter(k=>k.startsWith(prefix)).sort(),start=Number(cursor),end=start+limit;return {keys:all.slice(start,end).map(name=>({name})),list_complete:end>=all.length,cursor:String(end)}},values}}
const request=(path,method='GET',body,password='right',headers={})=>new Request('https://chat.xiaoman.xyz/memes/'+path,{method,headers:{...(password?{'X-Eunoia-Password':password}:{}),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...headers},body:body instanceof FormData?body:body?JSON.stringify(body):undefined})
const png=new Uint8Array([137,80,78,71,13,10,26,10,1,2,3]);
const upload=(name='猪猪抱抱',tags='贴贴，抱抱  猪猪 抱抱',bytes=png,type='image/png')=>{const f=new FormData();f.set('file',new File([bytes],'test.png',{type}));f.set('name',name);f.set('tags',tags);return f}
describe('private Worker meme library',()=>{
 it('paginates the complete private catalog without loading image bytes',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};const {meme}=await (await handleMemeRequest(request('api','POST',upload()),env)).json();const key=[...env.CHAT_KV.values.keys()].find(k=>k.startsWith('memes:')&&k.includes(':meta:')),prefix=key.slice(0,key.lastIndexOf(':')+1);for(let i=0;i<133;i++)await env.CHAT_KV.put(prefix+'test'+i,JSON.stringify({...meme,id:'test'+i}));const {code}=await (await handleMemeRequest(request('pair','POST'),env)).json();const {token}=await (await handleMemeRequest(request('bridge/claim','POST',{code},''),env)).json();const auth={Authorization:'Bearer '+token};const first=await (await handleMemeRequest(request('bridge/catalog','GET',null,'',auth),env)).json();expect(first.memes).toHaveLength(100);expect(first.nextCursor).toBeTruthy();expect(first.memes[0].dataUri).toBeUndefined();const last=await (await handleMemeRequest(request('bridge/catalog?cursor='+first.nextCursor,'GET',null,'',auth),env)).json();expect(last.memes).toHaveLength(34);expect(last.nextCursor).toBeNull();expect(new Set([...first.memes,...last.memes].map(m=>m.id)).size).toBe(134);expect((await handleMemeRequest(request('bridge/catalog','GET',null,''),env)).status).toBe(401);expect((await handleMemeRequest(request('bridge/catalog','POST',{},'',auth),env)).status).toBe(405)})
 it('uploads, searches metadata only, preserves bytes, edits and deletes',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};const posted=await handleMemeRequest(request('api','POST',upload()),env);expect(posted.status).toBe(201);const {meme}=await posted.json();expect(meme.tags).toBe('贴贴 抱抱 猪猪');const found=await (await handleMemeRequest(request('api?q=抱抱'),env)).json();expect(found.memes[0].id).toBe(meme.id);expect(found.memes[0].dataUri).toBeUndefined();const image=await handleMemeRequest(request('image/'+meme.id),env);expect([...new Uint8Array(await image.arrayBuffer())]).toEqual([...png]);expect((await handleMemeRequest(request('api/'+meme.id,'PATCH',{name:'晚安',tags:'晚安'}),env)).status).toBe(200);expect((await (await handleMemeRequest(request('api?q=晚安'),env)).json()).memes[0].name).toBe('晚安');expect((await handleMemeRequest(request('api/'+meme.id,'DELETE'),env)).status).toBe(200);expect((await handleMemeRequest(request('image/'+meme.id),env)).status).toBe(404)})
 it('rejects missing/wrong credentials and isolates existing user accounts',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};await env.CHAT_KV.put('user:other:settings','{}');const {meme}=await (await handleMemeRequest(request('api','POST',upload()),env)).json();expect((await handleMemeRequest(request('api','GET',null,''),env)).status).toBe(401);expect((await handleMemeRequest(request('api','GET',null,'wrong'),env)).status).toBe(401);expect((await handleMemeRequest(request('image/'+meme.id,'GET',null,'other'),env)).status).toBe(404);expect((await (await handleMemeRequest(request('api','GET',null,'other'),env)).json()).memes).toEqual([])})
 it('accepts GIFs and rejects spoofed/oversized images and disallowed origins',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};expect((await handleMemeRequest(request('api','POST',upload('动图','开心',new TextEncoder().encode('GIF89atest'),'image/gif')),env)).status).toBe(201);expect((await handleMemeRequest(request('api','POST',upload('坏文件','',new TextEncoder().encode('<svg/>'))),env)).status).toBe(400);expect((await handleMemeRequest(request('api','POST',upload('太大','',new Uint8Array(5*1024*1024+1))),env)).status).toBe(400);expect((await handleMemeRequest(request('api','GET',null,'right',{Origin:'https://evil.example'}),env)).status).toBe(403);const preflight=await handleMemeRequest(request('api','OPTIONS',null,'',{Origin:'https://eunoia.xiaoman.xyz'}),env);expect(preflight.status).toBe(204);expect(preflight.headers.get('Access-Control-Allow-Methods')).toContain('PATCH')})
 it('connects with a short-lived one-time code and grants only read access',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};const {meme}=await (await handleMemeRequest(request('api','POST',upload()),env)).json();const {code}=await (await handleMemeRequest(request('pair','POST'),env)).json();const claimed=await handleMemeRequest(request('bridge/claim','POST',{code},''),env);expect(claimed.status).toBe(200);const {token}=await claimed.json();expect((await handleMemeRequest(request('bridge/claim','POST',{code},''),env)).status).toBe(410);const auth={Authorization:'Bearer '+token};expect((await (await handleMemeRequest(request('bridge/search?q=抱抱','GET',null,'',auth),env)).json()).memes[0].id).toBe(meme.id);const image=await (await handleMemeRequest(request('bridge/image/'+meme.id,'GET',null,'',auth),env)).json();expect(image.dataUri).toBe('data:image/png;base64,'+btoa(String.fromCharCode(...png)));expect((await handleMemeRequest(request('bridge/search','POST',{},'',auth),env)).status).toBe(405);await handleMemeRequest(request('pair','DELETE'),env);expect((await handleMemeRequest(request('bridge/search','GET',null,'',auth),env)).status).toBe(401)})
 it('expired codes cannot be claimed and unrelated routes remain untouched',async()=>{const env={USER_PASSWORD:'right',CHAT_KV:kv()};const {code}=await (await handleMemeRequest(request('pair','POST'),env)).json();const key=[...env.CHAT_KV.values.keys()].find(k=>k.startsWith('memes:pair:'));const d=JSON.parse(env.CHAT_KV.values.get(key));env.CHAT_KV.values.set(key,JSON.stringify({...d,expiresAt:0}));expect((await handleMemeRequest(request('bridge/claim','POST',{code},''),env)).status).toBe(410);expect(await handleMemeRequest(new Request('https://chat.xiaoman.xyz/sync/get'),env)).toBeNull();expect((await handleMemeRequest(request('bridge/claim','POST',{code:'bad'},''),env)).status).toBe(400)})
})
